import { AOParcel } from '@/prisma/generated/zod';

export const mockAOParcel: AOParcel = {
  id: '1',
  parcel_name: 'Parcel 1',
  distance_from_primary_asset: '100 meters',
  lot_size: 2000.0,
  buildable_area: 1500.0,
  star_rating: '3 stars',
  owner: 'John Doe',
  name_mailing_address: 'John Doe',
  street_address_mailing_address: '123 Main St',
  street_address_2_mailing_address: 'Apt 4B',
  city_mailing_address: 'New York',
  state_mailing_address: 'NY',
  zip_mailing_address: '10001',
  county_parcel: 'Manhattan',
  land_use_category: 'Residential',
  apn: '1234567890',
  closest_primary_asset: 'Central Park',
  created_by: 'Admin',
  name_site_address: 'Parcel 1 Site',
  street_address_site_address: '123 Main St',
  street_address_2_site_address: 'Apt 4B',
  city_site_address: 'New York',
  state_site_address: 'NY',
  zip_site_address: '10001',
  asset_url: 'www.example.com/parcel1',
  total_acres_contiguous_parcels: '5 acres',
  company_name: 'Parcel Company',
  owner_group: 'Person',
  primary_owner_first_name: 'John',
  primary_owner_last_name: 'Doe',
  primary_owner: 'John Doe',
  address_line_2: 'Apt 4B',
  recipient: 'John Doe',
  census_zip: '10001',
  county_name: 'Manhattan',
  elevation: '33 feet',
  muni_id: '1',
  muni_name: 'New York',
  wetlands: 'No',
  county_id: '1',
  description: 'Parcel 1 description',
  latitude: '40.7128',
  longitude: '74.0060',
  wkt: null,
};
